# Generated by Django 6.1 on 2026-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hero_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_primary_button',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_secondary_button',
            field=models.CharField(default='Our Services', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_subtitle',
            field=models.TextField(default='Building intelligent websites, automation, and AI solutions for modern businesses.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_title',
            field=models.CharField(default='AI-Powered Digital Solutions', max_length=150),
        ),
    ]
